# synthetic-package: false

# The files are generated into the path specified by `arb-dir`
arb-dir: lib/l10n

# Or, specifically provide an output path:
output-dir: lib/l10n/generated/


template-arb-file: app_en.arb
output-localization-file: app_localizations.dart
untranslated-messages-file: untranslated.txt
