name: schulapp
description: "A new Flutter project."
publish_to: "none"
version: 0.2.0

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  archive: ^3.4.10
  flutter_colorpicker: ^1.0.3
  flutter_speed_dial: ^7.0.0
  go_router: ^12.1.1 #https://www.youtube.com/watch?v=b6Z885Z46cU
  google_fonts: ^6.1.0
  path: ^1.8.3
  path_provider: ^2.1.1
  file_picker: ^6.1.1
  document_file_save_plus: ^2.0.0
  animated_list_plus: ^0.5.2
  flutter_local_notifications: ^16.3.2
  timezone: ^0.9.2
  permission_handler: ^11.2.0
  tuple: ^2.0.2
  shared_preferences: ^2.2.2
  fl_chart: ^0.67.0
  flutter_localizations:
    sdk: flutter
  intl: any
  package_info_plus: ^7.0.0
  # fluent_ui: ^4.8.1
  # flutter_acrylic: ^1.1.3 #Window acrylic, mica & transparency effects for Flutter on Windows, macOS & Linux
  # provider: ^6.1.1
  # system_theme: ^2.3.1 #A flutter plugin to get the current system theme information
  # window_manager: ^0.3.7 #This plugin allows Flutter desktop apps to resizing and repositioning the window.

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  generate: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icon.png"
    background_color: "#1c1b1f"
    theme_color: "#25232a"
  windows:
    generate: true
    image_path: "assets/icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icon.png"
