name: schulapp
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_colorpicker: ^1.0.3
  flutter_speed_dial: ^7.0.0
  go_router: ^12.1.1 #https://www.youtube.com/watch?v=b6Z885Z46cU
  google_fonts: ^6.1.0
  path: ^1.8.3
  path_provider: ^2.1.1
  # fluent_ui: ^4.8.1
  # flutter_acrylic: ^1.1.3 #Window acrylic, mica & transparency effects for Flutter on Windows, macOS & Linux
  # provider: ^6.1.1
  # system_theme: ^2.3.1 #A flutter plugin to get the current system theme information
  # window_manager: ^0.3.7 #This plugin allows Flutter desktop apps to resizing and repositioning the window.

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
